package storage

import (
	"fmt"

	"github.com/TBD54566975/ssi-sdk/credential"

	cred "github.com/tbd54566975/ssi-service/internal/credential"
	"github.com/tbd54566975/ssi-service/internal/util"
	"github.com/tbd54566975/ssi-service/pkg/storage"
)

type StoreCredentialRequest struct {
	cred.CredentialContainer
}

type StoredCredential struct {
	// This ID is generated by the storage module upon first write
	ID string `json:"id"`

	CredentialID string `json:"credentialId"`

	// only one of these fields should be present
	Credential    *credential.VerifiableCredential `json:"credential,omitempty"`
	CredentialJWT *string                          `json:"token,omitempty"`

	Issuer       string `json:"issuer"`
	Subject      string `json:"subject"`
	Schema       string `json:"schema"`
	IssuanceDate string `json:"issuanceDate"`
}

func (sc StoredCredential) IsValid() bool {
	return sc.Credential != nil || sc.CredentialJWT != nil
}

func (sc StoredCredential) HasDataIntegrityCredential() bool {
	return sc.Credential != nil
}

func (sc StoredCredential) HasJWTCredential() bool {
	return sc.CredentialJWT != nil
}

type Storage interface {
	StoreCredential(request StoreCredentialRequest) error
	GetCredential(id string) (*StoredCredential, error)
	GetCredentialsByIssuer(issuer string) ([]StoredCredential, error)
	GetCredentialsBySubject(subject string) ([]StoredCredential, error)
	GetCredentialsBySchema(schema string) ([]StoredCredential, error)
	DeleteCredential(id string) error
}

func NewCredentialStorage(s storage.ServiceStorage) (Storage, error) {
	switch s.Type() {
	case storage.Bolt:
		gotBolt, ok := s.(*storage.BoltDB)
		if !ok {
			errMsg := fmt.Sprintf("trouble instantiating : %s", s.Type())
			return nil, util.LoggingNewError(errMsg)
		}
		boltStorage, err := NewBoltCredentialStorage(gotBolt)
		if err != nil {
			return nil, util.LoggingErrorMsg(err, "could not instantiate credential bolt storage")
		}
		return boltStorage, err
	default:
		errMsg := fmt.Errorf("unsupported storage type: %s", s.Type())
		return nil, util.LoggingError(errMsg)
	}
}
