# See https://golangci-lint.run/usage/configuration/ for reference.
run:
  concurrency: 16
  skip-dirs:
    - bin

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - typecheck
    - revive
    - gosec
    - govet
    - staticcheck
    - asasalint
    - durationcheck
    - gocritic
    - tparallel
    - usestdlibvars
    - tenv
#    - wrapcheck
#    - nilnil
#    - whitespace
#    - nilerr
    - makezero
    - prealloc
    - unparam
#    - goconst
#    - errorlint
#    - dupl
#    - unused
#    - tagliatelle

linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      # `camel` is used for `json` and `yaml` (can be overridden)
      # Default: {}
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
  gosec:
    config:
      G101:
        # We intentionally remove the 'cred' regex, to avoid false positives
        pattern: "(/i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer"

