# See https://golangci-lint.run/usage/configuration/ for reference.
run:
  concurrency: 16
  skip-dirs:
    - bin

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - asasalint
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - goimports
    - gosec
    - govet
    - ineffassign
    - makezero
    - prealloc
    - revive
    - staticcheck
    - tenv
    - tparallel
    - typecheck
    - unparam
    - unused
    - usestdlibvars
# TODO(andres): consider fixing and enabling the following.
#    - nilerr
#    - whitespace
#    - nilnil
#    - wrapcheck
#    - goconst
#    - dupl
#    - tagliatelle

linters-settings:
  gosec:
    config:
      G101:
        # We intentionally remove the 'cred' regex, to avoid false positives
        pattern: "(/i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer"

