apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    - port: {{ .Values.jaeger.service.port }}
      targetPort: {{ .Values.jaeger.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jaeger.replicaCount }}
  selector:
    matchLabels:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jaeger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
          imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.jaeger.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.jaeger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.jaeger.affinity }}
      affinity:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.jaeger.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.jaeger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 13 }}
      {{- end }}
