apiVersion: v2
name: ssi-service
description: A Helm chart for Kubernetes that deploys an SSI service environment
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: redis-ha
    version: 4.23.0
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
