name: Integration Tests

on:
  push:
    branches:
    - main
    - test/**
  pull_request:
      branches:
      - main

jobs:
  end2endtest:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.5
        cache: true

    - name: Install Mage
      run: go install github.com/magefile/mage

    - name: Start containers
      run: docker-compose -f "build/docker-compose.yml" up -d --build ssi redis uni-resolver driver-did-ion

    - name: End To End Test
      run: mage integration

    - name: Save Container Logs to Directory
      if: failure()
      run: |
        docker logs ssi > log/ssi_logs.txt
        docker cp ssi:/app/log .

    - name: Upload Logs as Artifact
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: log/*

    - name: Stop containers
      if: always()
      run: docker-compose -f "build/docker-compose.yml" down